spring:
  datasource:
    url: jdbc:h2:mem:talondb
    driver-class-name: org.h2.Driver
    username: sa
    password: password
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    database-platform: org.hibernate.dialect.H2Dialect
  h2:
    console:
      enabled: true
      path: /h2-console
server:
  port: 8080

# Security
security:
  api-key-header: Authorization
  api-key-prefix: ApiKey-v1
  api-key-value: test-api-key

springdoc:
  api-docs:
    path: /v3/api-docs
  swagger-ui:
    path: /swagger-ui.html
